from telugu_lexer import TeluguLexer
from telugu_parser import TeluguParser
from telugu_interpreter import TeluguInterpreter
from telugu_compiler import TeluguCompiler

class IntegratedFramework:
    def __init__(self):
        self.lexer = TeluguLexer()
        self.parser = TeluguParser()
        self.interpreter = TeluguInterpreter()
        self.compiler = TeluguCompiler()

    def run(self, code, mode='interpret'):
        if mode == 'interpret':
            return self.run_interpreter(code)
        elif mode == 'compile':
            return self.run_compiler(code)
        else:
            raise ValueError("Invalid mode. Use 'interpret' or 'compile'.")

    def run_interpreter(self, code):
        print("Running interpreter for rapid execution and debugging...")
        result = self.interpreter.interpret(code)
        print("Interpreter execution completed.")
        return result

    def run_compiler(self, code):
        print("Running compiler for optimization and deployment...")
        bytecode = self.compiler.compile(code)
        print("Compilation completed.")
        return bytecode

    def debug(self, code):
        print("Debugging mode: Running interpreter with step-by-step execution...")
        ast = self.parser.parse(code)
        self.debug_ast(ast)

    def debug_ast(self, node, indent=0):
        node_type = type(node).__name__
        print("  " * indent + f"Node: {node_type}")
        if hasattr(node, '__dict__'):
            for attr, value in node.__dict__.items():
                if isinstance(value, list):
                    print("  " * (indent + 1) + f"{attr}:")
                    for item in value:
                        self.debug_ast(item, indent + 2)
                elif not callable(value):
                    print("  " * (indent + 1) + f"{attr}: {value}")

if __name__ == "__main__":
    framework = IntegratedFramework()

    test_code = '''
    చర సంఖ్య = 10
    చేపాయిపిండి(సంఖ్య)

    యెడల (సంఖ్య > 5) {
        చేపాయిపిండి("సంఖ్య పెద్దది 5 కంటే")
    } లేక {
        చేపాయిపిండి("సంఖ్య చిన్నది లేదా సమానం 5కి")
    }
    '''

    print("=== Interpreter Mode ===")
    framework.run(test_code, mode='interpret')

    print("\n=== Compiler Mode ===")
    bytecode = framework.run(test_code, mode='compile')
    print("Generated Bytecode:", bytecode)

    print("\n=== Debug Mode ===")
    framework.debug(test_code)
