name: TeluguFusion CI/CD

on:
  push:
    branches: [ main, telugu_updates ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build TeluguFusion
      run: |
        cd తెలుగుఫ్యూజన్
        python build_telugufusion.py

    - name: Run tests
      run: |
        cd tests
        ./run_tests.sh

    - name: Run integration tests
      run: |
        cd tests
        ./run_integration_tests.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        ./deploy.sh
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

  update_docs:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Update documentation
      run: |
        cd docs
        ./update_docs.sh

    - name: Commit updated docs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/*
        git commit -m "తస్వయంచాలక పత్రాల నవీకరణ" || echo "No changes to commit"
        git push
