name: TeluguFusion CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Print Python version and installed packages
      run: |
        python --version
        pip list

    - name: Set PYTHONPATH and other environment variables
      run: |
        echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/src" >> $GITHUB_ENV
        echo "TELUGU_FUSION_HOME=${{ github.workspace }}" >> $GITHUB_ENV
        echo "DEBUG=1" >> $GITHUB_ENV

    - name: Run tests
      run: |
        python -m pytest src/

    - name: Build project
      run: |
        python src/compiler/telugu_compiler.py src/sample_program.tel

    - name: Run interpreter
      run: |
        python src/telugu_interpreter.py src/sample_program.tel

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add deployment steps here
